const upcomingEventsList = [
    {
        id:0,
        img: './Upcoming Events 1.1.png',
        title:"Canada Day Parade",
        date: '01/07/2022',
        link:'/Canada-Day-Parade',
        description:'',
        price: '',
        location:'',
    },
    {
        id:1,
        img: './Upcoming Events 1.1 (2).png',
        title:"Color Run",
        date: '26/08/2022',
        link:'/Color-Run',
        description:'',
        price: '',
        location:'',
    },
    {
        id:2,
        img: './Upcoming Events 1.1 (3).png',
        title:"Movies in the Park",
        date: '17/08/2022',
        link:'/Movies-in-the-Park',
        description:'',
        price: '',
        location:'',
    },
    {
        id:3,
        img: './Upcoming Events 1.1 (4).png',
        title:"Thanksgiving Festival",
        date: '09/09/2022',
        link:'Thanksgiving-Festival',
        description:'',
        price: '',
        location:'',
    },
    {
        id:4,
        img: './Upcoming Events 1.1.png',
        title:"Halloween Dance Party",
        date: '31/10/2022',
        link:'Halloween-Dance-Party',
        description:'',
        price: '',
        location:'',
    },
    {
        id:5,
        img: './Upcoming Events 1.1 (2).png',
        title:"Rememberance Day",
        date: '11/11/2022',
        link:'',
        description:'',
        price: '',
        location:'',
    },
    {
        id:7,
        img: './Upcoming Events 1.1 (3).png',
        title:"Christmas Market Opening",
        date: '15/12/2022',
        link:'Christmas-Market-Opening',
        description:'',
        price: '',
        location:'',
    },
]

export default upcomingEventsList;
