const upcomingEventsList = [
    {
        id:0,
        img: './Upcoming Events 1.1 (4).png',
        title:"Canada Day Parade",
        date: '01/07/2022',
        link:'/Canada-Day-Parade',
        description:'Enjoy the National Day, all Day. Go to the Old port and spend the first few hours of our National Day',
        price: 'Free',
        location:'Old Port or Mont-Royal Belvedaire',
    },
    {
        id:1,
        img: './Upcoming Events 1.1 (8).png',
        title:"Movies in the Park",
        date: '26/08/2022',
        link:'/Movies-in-the-Park',
        description:`Come join us! You can even bring your family, friend, or date to watch a new movie everytime we organize a movie night! 
                     You can either bring your own food, snacks and/or drinks or buy your dinner from our food-truck'`,
        price: '1$ per member! Free for kids and if it is your Birthday (ID may be required to verify your age)',
        location:'',
    },
    {
        id:2,
        img: './Upcoming Events 1.1 (7).png',
        title:"Color-Run",
        date: '17/08/2022',
        link:'/Color-run',
        description:'',
        price: '',
        location:'',
    },
    {
        id:3,
        img: './Upcoming Events 1.1 (4).png',
        title:"Thanksgiving Festival",
        date: '09/09/2022',
        link:'/Thanksgiving-Festival',
        description:`Not sure what to do this Thanksgiving? Come join us at Montreal's Annual Thanksgiving 
                    festival where you can meet new people, have dinner with us, and much more`,
        price: 'Single ticket: 5$, Couples Ticket: 7$, Free for kids under the age of 10',
        location:'Westmount Park, Angrignon Park',
    },
    {
        id:4,
        img: './Upcoming Events 1.1 (5).png',
        title:"Halloween Dance Party",
        date: '31/10/2022',
        link:'/Halloween-Dance-Party',
        description:'',
        price: '',
        location:'',
    },
    {
        id:5,
        img: './Upcoming Events 1.1 (6).png',
        title:"Sunlight Yoga for Adults",
        date: '11/15/2022',
        link:'/Yoga-for-adults',
        description:`Come have a nice stretch with us in the sunlight and get a chance to clense your aura with our guest instructor Charles Matkin!
                     Note: in case of bad weather, we will postpone the event and further notice will be given`,
        price: 'Free',
        location:'Park LaFontaine',
    },
    {
        id:7,
        img: './Upcoming Events 1.1 (7).png',
        title:"Christmas Market Opening",
        date: '15/12/2022',
        link:'/Christmas-Market-Opening',
        description:'',
        price: '',
        location:'',
    },
    {
        id:8,
        img: './Upcoming Events 1.1 (9).png',
        title:"Halloween Pumpkin Picking",
        date: '15/10/2022',
        link:'/Halloween-Pumpkin-Picking',
        description:'',
        price: '',
        location:'',
    },
    {
        id:9,
        img: './Upcoming Events 1.1 (10).png',
        title:"Toddlers Ballet Show",
        date: '15/12/2022',
        link:'/Toddlers-Ballet-Show',
        description:'',
        price: '',
        location:'',
    },
    {
        id:7,
        img: './Upcoming Events 1.1 (11).png',
        title:"Zoomba",
        date: '15/12/2022',
        link:'/Zoomba',
        description:'',
        price: '',
        location:'',
    },
]

export default upcomingEventsList;
